# Generated by Django 4.1 on 2023-04-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_server', '0002_todo3_delete_todo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo3',
            name='completed2',
            field=models.IntegerField(default=0),
        ),
    ]
