# Generated by Django 4.1 on 2023-04-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_server', '0003_todo3_completed2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo3',
            old_name='completed2',
            new_name='completed',
        ),
    ]
