# Generated by Django 4.1 on 2023-04-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_server', '0004_rename_completed2_todo3_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo3',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
